[k3s_master_node]
dudley-server-1.local ansible_user=dudley

[k3s_worker_nodes]
dudley-server-2.local ansible_user=dudley

[dudlab_cluster]
dudley-server-1.local ansible_user=dudley
dudley-server-2.local ansible_user=dudley

# Placeholder for 3rd node - uncomment when ready:
# dudley-server-3.local ansible_user=dudley
