- name: Configure MetalLB on Kubernetes
  hosts: k3s_master_node
  become: yes
  tasks:
    - name: Ensure MetalLB namespace exists
      command: kubectl create namespace metallb-system --dry-run=client -o yaml
      register: metallb_namespace

    - name: Apply MetalLB namespace
      command: kubectl apply -f -
      args:
        stdin: "{{ metallb_namespace.stdout }}"

    - name: Deploy MetalLB components
      command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.15.2/config/manifests/metallb-native.yaml

    - name: Copy MetalLB configuration file to master node
      copy:
        src: files/metallb-config.yaml
        dest: /tmp/metallb-config.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Apply MetalLB configuration
      command: kubectl apply -f /tmp/metallb-config.yaml
