---
- name: Update and upgrade packages on dudlab-cluster
  hosts: dudlab_cluster
  become: yes  # Run as sudo
  tasks:
    - name: Update APT package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes
