---
- name: Update and upgrade packages on dudlab-cluster
  hosts: dudlab_cluster
  become: true
  tasks:
    - name: Update APT package list
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: true
